/**
 * Version information for Aichaku
 * Generated by Nagare on 2025-07-11T02:08:23.516Z
 * 
 * Note: This template generates TypeScript code, not HTML.
 * The |> safe filter is used to output raw values without escaping.
 */

export const VERSION = "0.21.0";

export const BUILD_INFO = {
  buildDate: "2025-07-11T02:08:23.516Z",
  gitCommit: "b1e032b",
  buildEnvironment: "production",
  versionComponents: {
    major: 0,
    minor: 21,
    patch: 0,
    prerelease: null,
  },
} as const;

export const APP_INFO = {
  name: "Aichaku",
  description: "AI-optimized project methodology installer for Claude Code - brings affection (愛着) to your development workflow",
  repository: "https://github.com/RickCogley/aichaku",
  author: "Rick Cogley",
  homepage: "https://github.com/RickCogley/aichaku",
  license: "MIT",
} as const;
export const APP_METADATA = {} as const;
export const RELEASE_NOTES = {
  "version": "0.21.0",
  "date": "2025-07-11",
  "added": [
    "add custom standards system and folder reorganization (d2e0a2b)"
  ],
  "changed": [
    "update deno.lock for nagare v2.9.1 (9f584d4)",
    "bump nagare to v2.9.1 (eec3119)"
  ],
  "deprecated": [],
  "removed": [],
  "fixed": [
    "reset version to 0.20.0 for proper release (b1e032b)",
    "include deps.ts in publish configuration (ba22f02)"
  ],
  "security": []
} as const;