/**
 * Version information for Aichaku
 * Generated by Nagare on 2025-07-08T12:28:11.098Z
 * 
 * Note: This template generates TypeScript code, not HTML.
 * The |> safe filter is used to output raw values without escaping.
 */

export const VERSION = "0.12.0";

export const BUILD_INFO = {
  buildDate: "2025-07-08T12:28:11.098Z",
  gitCommit: "0f96c50",
  buildEnvironment: "production",
  versionComponents: {
    major: 0,
    minor: 12,
    patch: 0,
    prerelease: null,
  },
} as const;

export const APP_INFO = {
  name: "Aichaku",
  description: "AI-optimized project methodology installer for Claude Code - brings affection (愛着) to your development workflow",
  repository: "https://github.com/RickCogley/aichaku",
  author: "Rick Cogley",
  homepage: "https://github.com/RickCogley/aichaku",
  license: "MIT",
} as const;
export const APP_METADATA = {} as const;
export const RELEASE_NOTES = {
  "version": "0.12.0",
  "date": "2025-07-08",
  "added": [
    "improve installer next steps and add v0.11.0 release notes (0f96c50)"
  ],
  "changed": [],
  "deprecated": [],
  "removed": [],
  "fixed": [
    "update methodology file list to match actual repository structure (060615c)"
  ],
  "security": []
} as const;