# .github/workflows/publish.yml
name: Publish to JSR

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish"
        required: true
        type: string

# Enable provenance for JSR scoring
permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: ["2.4.x", "2.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Verify formatting
        run: deno run --allow-run --allow-read scripts/format-check.ts

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check **/*.ts

      - name: Run tests
        run: deno test --allow-read --allow-write --allow-env

      - name: Test CLI functionality
        run: |
          # Test CLI help
          deno run --allow-all cli.ts --help

          # Test init command (dry-run)
          deno run --allow-all cli.ts init --global --dry-run

  # Aichaku is a Deno-only tool designed specifically for Claude Code integration.
  # It uses Deno-specific APIs and is not intended for Node.js or Bun compatibility.
  # The tool is distributed via JSR for Deno users only.

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: read
      id-token: write # Required for provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Publish to JSR
        run: deno publish --allow-slow-types
        env:
          # JSR will automatically detect GitHub Actions provenance
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Generate and deploy documentation (optional)
  docs:
    needs: [test]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"

      - name: Generate documentation
        run: deno doc --html --name="Aichaku" mod.ts

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/
          retention-days: 30
